package Instagual;

public class Publicacion_propia_de_otro_usuario {
	public Ver_lista_de_publicaciones_del_usuario _ver_lista_de_publicaciones_del_usuario;
	public Ver_detalles_de_publicacion_vista_usuario_registrado _ver_detalles_de_publicacion_vista_usuario_registrado;
}