package Instagual;

public class Ver_detalles_de_publicacion_vista_publicacion_etiquetado extends Ver_detalles_de_publicacion_vista_usuario_registrado {
	//private Button _eliminarMencionB;
	public Buscar_vista_registrado _buscar_vista_registrado;
	public Ver_detalles_de_publicacion_vista_actividad__publicacion_y_mi_actividad _ver_detalles_de_publicacion_vista_actividad__publicacion_y_mi_actividad;
	public Publicacion_en_las_que_esta_etiquetado _publicacion_en_las_que_esta_etiquetado;

	public void EliminarMencion() {
		throw new UnsupportedOperationException();
	}
}