package Instagual;

public class Ver_detalles_de_publicacion_vista_publicacion_propia extends Ver_detalles_de_publicacion_vista_usuario_registrado {
	//private Button _editarDescripcionB;
	public Buscar_vista_registrado _buscar_vista_registrado;
	public Notificacion _notificacion;
	public Mi_actividad _mi_actividad;
	public Publicacion_propia _publicacion_propia;
	public Eliminar_publicacion_propia _eliminar_publicacion_propia;
	public Eliminar_comentario_de_publicacion_propia _eliminar_comentario_de_publicacion_propia;
}