package ual.mds2.Instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.NativeButton;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Actividad_ventana extends VerticalLayout {
	protected VerticalLayout verticalLayoutNotificacionActividad;
	protected HorizontalLayout horizontalLayoutNotificacionActividadUsuario;
	protected NativeButton nativeButtonImagenPerfil11;
	protected NativeButton nativeButtonNombreUsuario11;
	protected VerticalLayout verticalLayoutPublicaciones1;
	protected Label labelQueHizo1;
	protected Label labelQueHizo11;
	protected Panel panelListaPublicaciones1;
	protected VerticalLayout verticalLayoutListaPublicaciones1;
	protected HorizontalLayout horizontalLayoutListaPublicaciones1;
	protected VerticalLayout verticalLayoutPublicacion11;
	protected Image imagePublicacion11;
	protected VerticalLayout verticalLayoutPublicacion21;
	protected Image imagePublicacion21;
	protected VerticalLayout verticalLayoutSigueA;
	protected HorizontalLayout horizontalLayoutsigueA;
	protected Label labelSigueA;
	protected NativeButton nativeButtonNombreUsuario;

	public Actividad_ventana() {
		Design.read(this);
	}
}
