package ual.mds2.Instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.CheckBoxGroup;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ajustes_de_notificaciones_ventana extends VerticalLayout {
	protected VerticalLayout verticalLayoutAjusteNotificacionesContenido;
	protected Label labelAjustes;
	protected HorizontalLayout horizontalLAyoutSelecciones;
	protected VerticalLayout verticalLayoutAjustes1;
	protected CheckBoxGroup<java.lang.String> cBAjustes1;
	protected VerticalLayout verticalLayoutAjustes2;
	protected CheckBoxGroup<java.lang.String> cBAjustes2;

	public Ajustes_de_notificaciones_ventana() {
		Design.read(this);
	}
}
