package ual.mds2.Instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Buscar_ventana extends VerticalLayout {
	protected VerticalLayout verticalLayoutPantallaBase;
	protected HorizontalLayout horizontalLayoutBuscarTexto;
	protected Button buttonBuscar;
	protected TextField textFieldBuscar;
	protected Button buttonCerrarSesionAd;
	protected HorizontalLayout horizontalLayoutSelection;
	protected Button buttonUsuarios;
	protected Button buttonPublicaciones;
	protected VerticalLayout verticalLayoutListaBusqueda1;
	protected Panel panelBusqueda;
	protected VerticalLayout verticalLayoutListaBusqueda;

	public Buscar_ventana() {
		Design.read(this);
	}
}
