package ual.mds2.Instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Configuracion_ventana extends VerticalLayout {
	protected VerticalLayout verticalLayoutPantallaBase;
	protected HorizontalLayout horizontalLayoutMenuSuperior;
	protected Label labelConfiguracion;
	protected VerticalLayout verticalLayoutAjutesNotificacionesBase;
	protected VerticalLayout verticalLayoutAjusteNotificacionesContenido;
	protected Label labelAjustes;
	protected HorizontalLayout horizontalLAyoutSelecciones;
	protected VerticalLayout verticalLayoutAjustes1;
	protected CheckBox todas;
	protected CheckBox megusta;
	protected CheckBox comentarios;
	protected VerticalLayout verticalLayoutAjustes2;
	protected CheckBox seguir;
	protected CheckBox privada;
	protected CheckBox ocultarss;
	protected Button guardarConfig;
	protected VerticalLayout verticalLayoutBloqueadosDDBaja;
	protected Button buttonListaDeBloqueados;
	protected Button buttonDarseDeBaja;
	protected VerticalLayout verticalLayoutCerrarSesion;
	protected Button buttonCerrarSesion;

	public Configuracion_ventana() {
		Design.read(this);
	}
}
