package ual.mds2.Instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.Label;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Iniciar_sesion_ventana extends VerticalLayout {
	protected VerticalLayout verticalLayoutDatosEntrada;
	protected Label labelInstagual;
	protected TextField datosCorreo;
	protected PasswordField datosPassword;
	protected VerticalLayout verticalLayoutBotones;
	protected VerticalLayout verticalLayoutIniciarSesion;
	protected Button botonIniciarSesion;
	protected VerticalLayout verticalLayoutIniciarSesionMovil;
	protected Button botonRecuperarCuenta;
	protected Button botonRecuperarPassword;
	protected Label labelSinCuenta;
	protected Button botonRegistrarse;
	protected Button botonEntrarInvitado;

	public Iniciar_sesion_ventana() {
		Design.read(this);
	}
}
