package ual.mds2.Instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Publicacion_Pagina_Principal_ventana extends VerticalLayout {
	protected VerticalLayout verticalLayoutPublicacionPaginaPrincipal;
	protected HorizontalLayout horizontalLayoutUsuario;
	protected VerticalLayout verticalLayoutImagePerfil1;
	protected Image imageUsuario;
	protected VerticalLayout verticalLayoutINombreUsuario;
	protected Button nombreUsuario;
	protected VerticalLayout verticalLayoutPrevisualizacionImagenVideo11;
	protected Image imagePrimeraImagen;
	protected HorizontalLayout horizontalLayoutMenuMeGusta;
	protected VerticalLayout verticalLayoutBotonMeGusta;
	protected Button meGusta;
	protected VerticalLayout verticalLayoutMegustaInformacion;
	protected Label labelNumeroMeGusta;
	protected Label labelGenteMeGusta;

	public Publicacion_Pagina_Principal_ventana() {
		Design.read(this);
	}
}
