package ual.mds2.Instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Publicacion_en_las_que_esta_etiquetado_ventana extends VerticalLayout {
	protected HorizontalLayout horizontalLayoutUsuario;
	protected VerticalLayout verticalLayoutImagePerfil1;
	protected Image imageUsuario;
	protected VerticalLayout verticalLayoutINombreUsuario;
	protected Button nombreUsuario;
	protected VerticalLayout verticalLayoutElementoPublicar;
	protected Image imagePrueba;

	public Publicacion_en_las_que_esta_etiquetado_ventana() {
		Design.read(this);
	}
}
