package ual.mds2.Instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Publicar_ventana extends VerticalLayout {
	protected VerticalLayout verticalLayoutPublicar;
	protected HorizontalLayout horizontalLayoutPublicarMenuSuperior;
	protected Button buttonPublicar;
	protected VerticalLayout vLEtiqueta;
	protected HorizontalLayout hlEtiqueta;
	protected Label etiqueta;
	protected TextField tFEtiqueta;
	protected VerticalLayout verticalLayoutImagenesYLista;
	protected VerticalLayout verticalLayoutListaElementos;
	protected Panel panelListaImagenesVideos;
	protected HorizontalLayout hlImagenesVideos;
	protected VerticalLayout verticalLayoutGaleria;
	protected HorizontalLayout hLGaleria;
	protected HorizontalLayout hLGaleria1;
	protected Button buttonSubir;
	protected HorizontalLayout hLGaleria2;
	protected TextField uRLFoto;
	protected VerticalLayout verticalLayoutDescripcion;
	protected VerticalLayout vlMenciones;
	protected Label labelMenciones;
	protected HorizontalLayout hlMenciones;
	protected TextField mencion1;
	protected TextField mencion2;
	protected TextField tfDescripcion;

	public Publicar_ventana() {
		Design.read(this);
	}
}
