package ual.mds2.Instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Image;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Video;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Publicacion_propia_de_otro_usuario_ventana extends VerticalLayout {
	protected VerticalLayout verticalLayoutElementoPublicar;
	protected Image imagePrueba;
	protected Video videoPrueba;

	public Publicacion_propia_de_otro_usuario_ventana() {
		Design.read(this);
	}
}
