package ual.mds2.Instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ver_detalles_de_publicacion_ventana extends VerticalLayout {
	protected HorizontalLayout horizontalLayoutMenuSuperiorPublicacion;
	protected Label labelPublicacion;
	protected HorizontalLayout horizontalLayoutPublicacionUsuario;
	protected VerticalLayout verticalLayoutImagenUsuario1;
	protected Image imagenPerfil;
	protected VerticalLayout verticalLayoutNombreUsuario1;
	protected Button nombreUsuario;
	protected VerticalLayout verticalLayoutCompartir;
	protected Button buttonCompartir;
	protected VerticalLayout verticalLayoutEliminar;
	protected Button buttonEliminarPublicacion;
	protected VerticalLayout verticalLayoutListaElementos;
	protected Panel panelListaElementos;
	protected HorizontalLayout horizontalLayoutListaElementos;
	protected HorizontalLayout horizontalLayoutMeGustaComentarios;
	protected VerticalLayout verticalLayoutIconosMegustaComentarios;
	protected VerticalLayout verticalLayoutMegustaIcono;
	protected Button meGusta;
	protected VerticalLayout verticalLayoutComentariosIcono;
	protected Button verComentarios;
	protected VerticalLayout verticalLayoutMegustaComentarios2;
	protected VerticalLayout verticalLayoutMegustaGente;
	protected Button labelMegusta;
	protected VerticalLayout verticalLayoutVerComentarios;
	protected Label labelVerComentarios;
	protected VerticalLayout verticalLayoutDescripcion;
	protected Label labelDescripcionPublicacion;
	protected Button buttonEliminarMencion;
	protected VerticalLayout vlMencionados;
	protected Label mencionados;

	public Ver_detalles_de_publicacion_ventana() {
		Design.read(this);
	}
}
