package ual.mds2.Instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ver_lista_de_comentarios_ventana extends VerticalLayout {
	protected HorizontalLayout horizontalLayoutMenuSuperiorComentarios;
	protected Button bAtras;
	protected Label labelComentarios;
	protected VerticalLayout verticalLayoutDescripcionPublicador;
	protected HorizontalLayout horizontalLayoutUsuarioComentador;
	protected VerticalLayout verticalLayoutImagenUsuario;
	protected Image imageNombreUsuario;
	protected VerticalLayout verticalLayoutNombreUsuario;
	protected Button nativeButtonUsuario;
	protected Label labelDescripPublicacion12;
	protected VerticalLayout verticalLayoutIconoMegustaComentarios;
	protected Button buttonDarMeGustaComentario;
	protected Panel panelListaComentarios;
	protected VerticalLayout listaComentarios;
	protected HorizontalLayout horizontalLayoutEscribirComentario;
	protected TextField textFieldComentario;
	protected Button buttonPublicar;

	public Ver_lista_de_comentarios_ventana() {
		Design.read(this);
	}
}
