package ual.mds2.Instagual;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Image;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class Ver_perfil_de_usuario_vista_no_registrado_privada_ventana extends VerticalLayout {
	protected VerticalLayout verticalLayoutPantallaBase;
	protected HorizontalLayout horizontalLayoutMenuSuperiorVerPerfil;
	protected VerticalLayout verticalLayoutAtrasVerPerfil;
	protected VerticalLayout verticalLayoutConfiguracionVerPerfil;
	protected Button buttonConfiguracionVerPerfil;
	protected VerticalLayout verticalLayoutVerPerfilDatosSBE;
	protected HorizontalLayout horizontalLayoutDatosPerfil;
	protected VerticalLayout verticalLayoutImagenPerfil;
	protected Image imagePerfil;
	protected VerticalLayout verticalLayoutInformacionEditarPerfil;
	protected VerticalLayout verticalLayoutSeguidoresSeguidos;
	protected Label labelSeguidores;
	protected Label labelSeguidos;
	protected VerticalLayout verticalLayoutEditarPerfil;
	protected Button buttonEditarPerfil;
	protected Button buttonEliminarPerfil;
	protected VerticalLayout verticalLayoutAccionesVerPerfil;
	protected VerticalLayout verticalLayoutSeguir;
	protected Button buttonSeguir;
	protected VerticalLayout verticalLayoutBloquear;
	protected Button buttonBloquear;
	protected VerticalLayout verticalLayoutNombreUsuario;
	protected Label labelNombreDeUsuario;
	protected VerticalLayout verticalLayoutOpcionesMenu;
	protected HorizontalLayout horizontalLayoutOpcionesMenu;
	protected VerticalLayout verticalLayoutMisActividades;
	protected Button menuActividades;
	protected VerticalLayout verticalLayoutPublicaionesUsuario;
	protected Button menuPublicaciones;
	protected VerticalLayout verticalLayoutPublicacionesUsuarioEtiquetado;
	protected Button menuEtiquetadas;
	protected VerticalLayout verticalLayoutListas;
	protected Panel panelLista;
	protected VerticalLayout verticalLayoutLista;

	public Ver_perfil_de_usuario_vista_no_registrado_privada_ventana() {
		Design.read(this);
	}
}
